{
 "title": "MQTT Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "job",
    "query": "label_values(mqtt_server_uptime,job)"
   },
   {
    "name": "namespace",
    "query": "label_values(mqtt_server_uptime, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "MQTT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mqtt_clients_connected{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "connected"
    },
    {
     "expr": "mqtt_clients_persisted{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "persisted"
    },
    {
     "expr": "sum(mqtt_clients_total{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(mqtt_clients_maximum{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "maximum"
    }
   ]
  },
  {
   "title": "Publish Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mqtt_packets_publish_sent {job=\"$job\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "publish_sent"
    },
    {
     "expr": "-sum(rate(mqtt_packets_publish_recv {job=\"$job\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "publish_recv"
    },
    {
     "expr": "sum(rate(mqtt_packets_puback_sent {job=\"$job\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "puback_sent"
    },
    {
     "expr": "-sum(rate(mqtt_packets_puback_recv {job=\"$job\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "puback_recv"
    },
    {
     "expr": "sum(rate(mqtt_packets_pubrec_sent {job=\"$job\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "pubrec_sent"
    },
    {
     "expr": "-sum(rate(mqtt_packets_pubrec_recv {job=\"$job\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "pubrec_recv"
    },
    {
     "expr": "sum(rate(mqtt_packets_pubrel_sent {job=\"$job\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "pubrel_sent"
    },
    {
     "expr": "-sum(rate(mqtt_packets_pubrel_recv {job=\"$job\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "pubrel_recv"
    },
    {
     "expr": "sum(rate(mqtt_packets_pubcomp_sent {job=\"$job\",instance=\"$instance\"}[1m]))",
     "legendFormat": "pubcomp_sent"
    },
    {
     "expr": "-sum(rate(mqtt_packets_pubcomp_recv {job=\"$job\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "pubcomp_recv"
    }
   ]
  },
  {
   "title": "Packets rate (total)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mqtt_packets_total_sent{namespace=\"$namespace\", job=\"$job\"}[1m]))",
     "legendFormat": "sent"
    },
    {
     "expr": "-sum(rate(mqtt_packets_total_recv{namespace=\"$namespace\", job=\"$job\"}[1m]))",
     "legendFormat": "recv"
    }
   ]
  },
  {
   "title": "Bytes rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mqtt_bytes_total_sent{namespace=\"$namespace\", job=\"$job\"}[1m]))",
     "legendFormat": "sent"
    },
    {
     "expr": "-sum(rate(mqtt_bytes_total_recv{namespace=\"$namespace\", job=\"$job\"}[1m]))",
     "legendFormat": "recv"
    }
   ]
  },
  {
   "title": "Inflight packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(mqtt_packets_inflight_sent{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "sent"
    },
    {
     "expr": "sum(mqtt_packets_inflight_recv{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "recv"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mqtt_subscriptions_total{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(mqtt_subscriptions_maximum{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "maximum"
    }
   ]
  },
  {
   "title": "Packets rate (by packet type)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(mqtt_packets_auth_recv{job=\"$job\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "auth_recv"
    },
    {
     "expr": "sum(rate(mqtt_packets_auth_sent{job=\"$job\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "auth_sent"
    },
    {
     "expr": "-sum(rate(mqtt_packets_connected_recv{job=\"$job\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "connected_recv"
    },
    {
     "expr": "sum(rate(mqtt_packets_disconnect_sent{job=\"$job\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "disconnect_sent"
    },
    {
     "expr": "-sum(rate(mqtt_packets_disconnect_recv{job=\"$job\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "disconnect_recv"
    },
    {
     "expr": "sum(rate(mqtt_packets_connack_sent{job=\"$job\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "conack_sent"
    },
    {
     "expr": "-sum(rate(mqtt_packets_pingreq_recv{job=\"$job\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "ping_recv"
    },
    {
     "expr": "sum(rate(mqtt_packets_pingreq_sent {job=\"$job\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "pong_sent"
    }
   ]
  },
  { "title": "Go runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Go Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "go_info{job=\"$job\", namespace=\"$namespace\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Go Threads",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "go_threads{job=\"$job\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 27 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(mqtt_server_uptime{namespace=\"$namespace\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Go Memstat",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{job=\"$job\", namespace=\"$namespace\"})",
     "legendFormat": "allocated"
    },
    {
     "expr": "sum(go_memstats_buck_hash_sys_bytes{job=\"$job\", namespace=\"$namespace\"})",
     "legendFormat": "profiling bucket"
    },
    {
     "expr": "sum(go_memstats_heap_alloc_bytes{job=\"$job\", namespace=\"$namespace\"})",
     "legendFormat": "heap allocated"
    },
    {
     "expr": "sum(go_memstats_heap_inuse_bytes {job=\"$job\", namespace=\"$namespace\"})",
     "legendFormat": "heap inuse"
    },
    {
     "expr": "sum(go_memstats_heap_idle_bytes{job=\"$job\", namespace=\"$namespace\"})",
     "legendFormat": "heap idle"
    }
   ]
  },
  {
   "title": "GC duration (us)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 36 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"$job\", namespace=\"$namespace\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 36 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"$job\", namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}-{{quantile}}"
    }
   ]
  },
  { "title": "Process Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"$job\", namespace=\"$namespace\"})",
     "legendFormat": "rss"
    },
    {
     "expr": "sum(process_virtual_memory_bytes{job=\"$job\", namespace=\"$namespace\"})",
     "legendFormat": "virtual"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } }
 ]
}